"""AWS Bedrock client for AI-powered anomaly analysis.

Wraps the AWS Bedrock Converse API to send log analysis requests and parse
structured responses. Implements exponential backoff retry for transient
errors, structured logging of token usage and latency, and health status
caching for the ``/health`` endpoint.

Typical usage::

    from app.services.bedrock_client import BedrockClient
    from app.config import get_settings

    client = BedrockClient(settings=get_settings(), app_state=app.state)
    result = client.analyze(
        service="payment-service",
        window_start=datetime(2025, 1, 15, 14, 26),
        window_end=datetime(2025, 1, 15, 14, 32),
        error_rate=0.67,
        log_messages=["Connection timeout", "Payment failed"],
    )
"""

import json
import logging
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

import boto3
from botocore.exceptions import ClientError

from app.config import Settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MAX_RETRIES: int = 3
RETRY_BASE_DELAY_SECONDS: float = 1.0

RETRYABLE_ERROR_CODES: set = {
    "ThrottlingException",
    "ServiceUnavailableException",
    "ModelTimeoutException",
}

PROMPT_TEMPLATE: str = """\
You are an SRE anomaly analysis assistant. Analyse the following log data \
and respond in the exact JSON format specified.

Service: {service}
Time Window: {window_start} to {window_end} (UTC)
Error Rate: {error_rate:.1%} ({error_count} errors out of {total_count} log entries)

Log Messages (most recent {sample_size} entries):
{log_messages_block}

Respond with ONLY valid JSON in this exact format — no markdown, no explanation outside the JSON:
{{
  "anomaly_score": <float between 0.0 and 1.0>,
  "summary": "<one to three sentence plain-text explanation of the anomaly pattern>"
}}

Scoring guide:
- 0.0–0.39: Low severity — isolated errors, likely transient
- 0.40–0.69: Medium severity — degraded service, warrants investigation
- 0.70–0.89: High severity — significant service impact, escalate
- 0.90–1.0:  Critical severity — service failure or cascade, immediate action required"""


# ---------------------------------------------------------------------------
# Data classes and exceptions
# ---------------------------------------------------------------------------


@dataclass
class BedrockAnalysisResult:
    """Result of a successful Bedrock anomaly analysis call.

    Attributes:
        anomaly_score: Numeric severity score between 0.0 and 1.0.
        summary: Plain-text explanation of the anomaly pattern.
        input_tokens: Number of input tokens consumed by the API call.
        output_tokens: Number of output tokens generated by the API call.
        latency_ms: Wall-clock latency of the API call in milliseconds.
    """

    anomaly_score: float
    summary: str
    input_tokens: int
    output_tokens: int
    latency_ms: float


class BedrockParseError(Exception):
    """Raised when the Bedrock response cannot be parsed into the expected structure.

    This includes malformed JSON, missing required keys, or an anomaly_score
    outside the valid [0.0, 1.0] range.

    Attributes:
        message: Human-readable description of the parsing failure.
    """

    def __init__(self, message: str) -> None:
        """Initialise BedrockParseError with a descriptive message.

        Args:
            message: Description of the parsing failure.
        """
        super().__init__(message)
        self.message = message


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class BedrockClient:
    """AWS Bedrock Converse API wrapper for anomaly analysis.

    Constructs prompts from log data, invokes the Converse API with retry
    logic, parses structured responses, and updates the application health
    cache after every inference call.

    Args:
        settings: Application settings instance containing AWS region,
            model ID, and max log sample configuration.
        app_state: Optional FastAPI application state object. When provided,
            ``bedrock_health`` is updated after every inference call.
    """

    def __init__(self, settings: Settings, app_state: Optional[Any] = None) -> None:
        """Initialise the Bedrock client with AWS credentials and configuration.

        Args:
            settings: Application settings with AWS_REGION, BEDROCK_MODEL_ID,
                and BEDROCK_MAX_LOG_SAMPLE.
            app_state: Optional FastAPI app.state for health status updates.
        """
        self._settings = settings
        self._app_state = app_state
        self._client = boto3.client(
            "bedrock-runtime",
            region_name=settings.AWS_REGION,
        )

    def analyze(
        self,
        service: str,
        window_start: datetime,
        window_end: datetime,
        error_rate: float,
        log_messages: List[str],
    ) -> BedrockAnalysisResult:
        """Invoke Bedrock Converse API and return a parsed analysis result.

        Constructs a prompt from the provided log data, sends it to the
        configured Bedrock model, parses the JSON response, and logs token
        usage and latency. Updates ``app.state.bedrock_health`` after every
        call (success or failure).

        Args:
            service: Name of the affected service.
            window_start: Start of the anomaly time window (UTC).
            window_end: End of the anomaly time window (UTC).
            error_rate: Computed error rate within the window (0.0–1.0).
            log_messages: List of log message strings from the window.

        Returns:
            A ``BedrockAnalysisResult`` containing the anomaly score, summary,
            token usage, and latency.

        Raises:
            BedrockParseError: If the model response cannot be parsed into
                the expected JSON structure or the score is out of range.
            ClientError: If the AWS API call fails with a non-retryable error
                after exhausting all retry attempts.
        """
        # Cap log messages at BEDROCK_MAX_LOG_SAMPLE (most recent entries)
        max_sample = self._settings.BEDROCK_MAX_LOG_SAMPLE
        capped_messages = log_messages[-max_sample:] if len(log_messages) > max_sample else log_messages

        # Build the prompt
        prompt = self._build_prompt(
            service=service,
            window_start=window_start,
            window_end=window_end,
            error_rate=error_rate,
            log_messages=capped_messages,
        )

        # Invoke with retry
        start_time = time.perf_counter()
        try:
            raw_response = self._invoke_with_retry(prompt)
        except (ClientError, BedrockParseError):
            self._update_health(is_success=False)
            raise
        except Exception:
            self._update_health(is_success=False)
            raise

        elapsed_ms = (time.perf_counter() - start_time) * 1000

        # Parse the response
        try:
            score, summary = self._parse_response(raw_response)
        except BedrockParseError:
            self._update_health(is_success=False)
            raise

        # Extract token usage
        input_tokens, output_tokens = self._extract_token_usage(raw_response)

        # Log token usage and latency as structured JSON
        logger.info(
            json.dumps({
                "event": "bedrock_inference_complete",
                "service": service,
                "model_id": self._settings.BEDROCK_MODEL_ID,
                "anomaly_score": score,
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "latency_ms": round(elapsed_ms, 2),
            })
        )

        # Update health status on success
        self._update_health(is_success=True)

        return BedrockAnalysisResult(
            anomaly_score=score,
            summary=summary,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            latency_ms=round(elapsed_ms, 2),
        )

    def _build_prompt(
        self,
        service: str,
        window_start: datetime,
        window_end: datetime,
        error_rate: float,
        log_messages: List[str],
    ) -> str:
        """Construct the analysis prompt from log data.

        Args:
            service: Name of the affected service.
            window_start: Start of the anomaly time window.
            window_end: End of the anomaly time window.
            error_rate: Computed error rate (0.0–1.0).
            log_messages: Capped list of log message strings.

        Returns:
            The formatted prompt string ready for the Converse API.
        """
        total_count = len(log_messages)
        error_count = round(error_rate * total_count)
        log_messages_block = "\n".join(
            f"  - {msg}" for msg in log_messages
        )

        return PROMPT_TEMPLATE.format(
            service=service,
            window_start=window_start.strftime("%Y-%m-%dT%H:%M:%SZ"),
            window_end=window_end.strftime("%Y-%m-%dT%H:%M:%SZ"),
            error_rate=error_rate,
            error_count=error_count,
            total_count=total_count,
            sample_size=len(log_messages),
            log_messages_block=log_messages_block,
        )

    def _invoke_with_retry(self, prompt: str) -> dict:
        """Invoke the Bedrock Converse API with exponential backoff retry.

        Retries on ThrottlingException, ServiceUnavailableException, and
        ModelTimeoutException up to MAX_RETRIES attempts with doubling delay
        (1s, 2s, 4s).

        Args:
            prompt: The formatted prompt string to send to the model.

        Returns:
            The raw API response dictionary from the Converse API.

        Raises:
            ClientError: If the API call fails with a non-retryable error
                or all retry attempts are exhausted.
        """
        last_exception: Optional[ClientError] = None

        for attempt in range(MAX_RETRIES):
            try:
                response = self._client.converse(
                    modelId=self._settings.BEDROCK_MODEL_ID,
                    messages=[
                        {
                            "role": "user",
                            "content": [{"text": prompt}],
                        }
                    ],
                )
                return response
            except ClientError as exc:
                last_exception = exc
                error_code = exc.response["Error"]["Code"]

                if error_code not in RETRYABLE_ERROR_CODES or attempt == MAX_RETRIES - 1:
                    logger.error(
                        json.dumps({
                            "event": "bedrock_invoke_failed",
                            "error_code": error_code,
                            "attempt": attempt + 1,
                            "max_retries": MAX_RETRIES,
                            "message": str(exc),
                        })
                    )
                    raise

                delay = RETRY_BASE_DELAY_SECONDS * (2 ** attempt)
                logger.warning(
                    json.dumps({
                        "event": "bedrock_invoke_retry",
                        "error_code": error_code,
                        "attempt": attempt + 1,
                        "delay_seconds": delay,
                    })
                )
                time.sleep(delay)

        # This should not be reached, but satisfies type checker
        raise last_exception  # type: ignore[misc]

    def _parse_response(self, raw_response: dict) -> tuple:
        """Extract anomaly_score and summary from the Bedrock Converse response.

        Validates that the response contains the expected JSON structure and
        that the anomaly_score is within the valid [0.0, 1.0] range.
        Handles responses wrapped in markdown code blocks.

        Args:
            raw_response: The raw API response dictionary from the Converse API.

        Returns:
            A tuple of (anomaly_score, summary).

        Raises:
            BedrockParseError: If the response cannot be parsed into the
                expected structure or the score is out of range.
        """
        try:
            content_text = raw_response["output"]["message"]["content"][0]["text"]

            # Strip markdown code fences if present
            text = content_text.strip()
            if text.startswith("```"):
                # Remove opening fence (```json or ```)
                first_newline = text.find("\n")
                if first_newline != -1:
                    text = text[first_newline + 1:]
                # Remove closing fence
                if text.rstrip().endswith("```"):
                    text = text.rstrip()[:-3].rstrip()

            parsed = json.loads(text)
            score = float(parsed["anomaly_score"])
            summary = str(parsed["summary"])

            if not (0.0 <= score <= 1.0):
                raise BedrockParseError(
                    f"anomaly_score {score} out of range [0.0, 1.0]"
                )

            return score, summary
        except BedrockParseError:
            raise
        except (KeyError, json.JSONDecodeError, TypeError, ValueError) as exc:
            raise BedrockParseError(
                f"Failed to parse Bedrock response: {exc}"
            ) from exc

    def _extract_token_usage(self, raw_response: dict) -> tuple:
        """Extract input and output token counts from the API response.

        Args:
            raw_response: The raw API response dictionary from the Converse API.

        Returns:
            A tuple of (input_tokens, output_tokens). Returns (0, 0) if
            token usage information is not available in the response.
        """
        try:
            usage = raw_response.get("usage", {})
            input_tokens = int(usage.get("inputTokens", 0))
            output_tokens = int(usage.get("outputTokens", 0))
            return input_tokens, output_tokens
        except (TypeError, ValueError):
            return 0, 0

    def _update_health(self, is_success: bool) -> None:
        """Update the application Bedrock health cache after an inference call.

        Sets the cached status to 'ok' on success or 'degraded' on failure,
        along with the current timestamp and a descriptive message.

        Args:
            is_success: Whether the inference call completed successfully.
        """
        if self._app_state is None:
            return

        now = datetime.utcnow()

        if is_success:
            self._app_state.bedrock_health = {
                "status": "ok",
                "last_checked_at": now,
                "message": "Last inference call succeeded",
            }
        else:
            self._app_state.bedrock_health = {
                "status": "degraded",
                "last_checked_at": now,
                "message": "Last inference call failed",
            }
